version: '3.8'

services:
  database:
    build: 
      context: .
      dockerfile: ./data/DockerFile 
    container_name: figs 
    volumes:  
      - ./titanic.db:/app/titanic.db

  flask: 
    build:
      context: ./flask
      dockerfile: DockerFile
    container_name: fl_container
    ports:
      - "5000:5000"
    depends_on: 
      - database
    volumes:
      - ./flask:/app
      - ./titanic.db:/app/titanic.db

  streamlit: 
    build:
      context: ./streamlit
      dockerfile: DockerFile
    container_name: figs1
    ports:
      - "8501:8501"
    depends_on: 
      - flask
    volumes:
      - ./streamlit:/app
